# Generated by Django 5.0.3 on 2024-04-03 19:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_category',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='slug',
        ),
        migrations.AddField(
            model_name='bill',
            name='measure_unit',
            field=models.CharField(default='watt-hour', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='month_paid',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='billcategory',
            name='color',
            field=models.CharField(default='red', max_length=30),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billsubcategory'),
        ),
    ]
