# Generated by Django 5.0.3 on 2024-04-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bills", "0001_initial"),
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="buildings.building"
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bills.billtype"
            ),
        ),
    ]
