# Generated by Django 5.0.3 on 2024-04-03 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billsubcategory_remove_bill_bill_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billcategory',
            name='building',
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billsubcategory',
            name='bill_category',
            field=models.ForeignKey(default='Electricity', on_delete=django.db.models.deletion.CASCADE, to='bills.billcategory'),
        ),
    ]
