# Generated by Django 5.0.3 on 2024-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_billsubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
