# Generated by Django 5.0.3 on 2024-04-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_building_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billcategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='billsubcategory',
            old_name='name',
            new_name='sub_category_name',
        ),
    ]
