# Generated by Django 5.0.3 on 2024-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_rename_name_billcategory_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='price',
            new_name='tariff',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='billsubcategory',
            name='measure_unit',
            field=models.CharField(default='watt-hour', max_length=10),
        ),
    ]
