# Generated by Django 5.0.3 on 2024-04-23 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
