# Generated by Django 5.0.3 on 2024-04-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rename_price_bill_tariff_remove_bill_measure_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='month_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
