# Generated by Django 5.0.3 on 2024-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_bill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcategory',
            name='color',
            field=models.CharField(default='Red', max_length=30),
        ),
    ]
