# Generated by Django 5.0.3 on 2024-04-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_billcategory_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
    ]
