# Generated by Django 5.0.3 on 2024-04-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_month_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(verbose_name='10-04-2024'),
        ),
    ]
