# Generated by Django 5.0.3 on 2024-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_bill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default='14-04-2024'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tariff',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
    ]
