# Generated by Django 5.0.3 on 2024-04-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_rename_sub_category_name_billsubcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsubcategory',
            old_name='name',
            new_name='sub_category_name',
        ),
    ]
