# Generated by Django 5.0.3 on 2024-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_rename_name_billsubcategory_sub_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_sum',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tariff',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
