# Generated by Django 5.0.3 on 2024-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_bill_bill_sum_alter_bill_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsubcategory',
            name='tariff',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
    ]
