# Generated by Django 5.0.3 on 2024-04-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_billsubcategory_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='bill_sub_category',
        ),
        migrations.RemoveField(
            model_name='building',
            name='user',
        ),
    ]
