# Generated by Django 5.0.3 on 2024-04-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_remove_building_bill_sub_category_and_more'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.RemoveField(
            model_name='billcategory',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='billsubcategory',
            name='is_selected',
        ),
        migrations.AlterField(
            model_name='bill',
            name='tariff',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
