# Generated by Django 5.0.3 on 2024-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_alter_bill_building_remove_billcategory_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
