# Generated by Django 5.0.3 on 2024-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_alter_bill_bill_sum'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='bill_sub_category',
            field=models.ManyToManyField(blank=True, related_name='bill_sub_category', to='bills.billsubcategory'),
        ),
    ]
