# Generated by Django 5.0.3 on 2024-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_bill_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='currency',
            field=models.CharField(default='UAN', max_length=10),
        ),
    ]
